### ISSUE TITLE
Problem building esig on manylinux 64x2010 build

### ISSUE THREAD

**Issue by jambo6** [datasig-ac-uk/esig#76]
Hi, 

I am unable to build esig on a manylinux64x2010 system. It says there is a problem importing the _recombine module. 

I have pasted the error below. 

Is there an issue here that can be fixed?

```
src/C_tosig.c:16:10: fatal error: _recombine.h: No such file or directory
   #include "_recombine.h"
            ^~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for esig
  Running setup.py clean for esig
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44619 sha256=f40b91b3c43e73883aee35350154ac0b14002e89c2ca55ad735a05cc694285d0
  Stored in directory: /root/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
  Building wheel for contextvars (setup.py): started
  Building wheel for contextvars (setup.py): finished with status 'done'
  Created wheel for contextvars: filename=contextvars-2.4-py3-none-any.whl size=7664 sha256=5fa0ad18194c801762fe732f1ba7e9955e7b6a981bbc930125bd6b65b854cd3b
  Stored in directory: /root/.cache/pip/wheels/41/11/53/911724983aa48deb94792432e14e518447212dd6c5477d49d3
  Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'done'
  Created wheel for psutil: filename=psutil-5.7.3-cp36-cp36m-linux_x86_64.whl size=285183 sha256=042b20793fd4d24e15cbedb2a48c8a56efe7ffd37aec6e1d76d3c3c7e3b65289
  Stored in directory: /root/.cache/pip/wheels/fa/ad/67/90bbaacdcfe970960dd5158397f23a6579b51d853720d7856d
  Building wheel for locket (setup.py): started
  Building wheel for locket (setup.py): finished with status 'done'
  Created wheel for locket: filename=locket-0.2.0-py3-none-any.whl size=4039 sha256=5edb32449913743f9201834b71b6ff7c1a3b7dc5eb7251f8f00307a5185ec88f
  Stored in directory: /root/.cache/pip/wheels/21/ca/95/1e41f9a9a7a06ba06874ad2bf0eac88e7ba02fe9a6ff26c77d
Successfully built catch22 pyyaml contextvars psutil locket
Failed to build esig
Installing collected packages: catch22, cython, numpy, esig, llvmlite, numba, six, python-dateutil, pytz, pandas, scipy, urllib3, patsy, statsmodels, threadpoolctl, joblib, scikit-learn, pmdarima, pyparsing, packaging, py, zipp, importlib-metadata, toml, pluggy, attrs, iniconfig, pytest, coverage, pytest-cov, cycler, kiwisolver, pillow, matplotlib, seaborn, scikit-posthocs, pyyaml, toolz, locket, partd, fsspec, dask, tqdm, chardet, certifi, idna, requests, immutables, contextvars, msgpack, sortedcontainers, heapdict, zict, click, tornado, cloudpickle, psutil, tblib, distributed, tsfresh
    Running setup.py install for esig: started
    Running setup.py install for esig: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/_internal/cpython-3.6.12/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ele2643x/esig/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ele2643x/esig/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4rzp71_e/install-record.txt --single-version-externally-managed --compile --install-headers /opt/_internal/cpython-3.6.12/include/python3.6m/esig
         cwd: /tmp/pip-install-ele2643x/esig/
    Complete output (18 lines):
    esig_install> Starting esig installer...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ele2643x/esig/setup.py", line 2, in <module>
        from tools import install_helpers as helpers
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 935, in <module>
        CONFIGURATION = InstallationConfiguration()
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 569, in __init__
        self.__run_checks()
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 601, in __run_checks
        ComponentChecker.check_libraries(self.library_dirs)
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 287, in check_libraries
        message_printer(missing_libraries_message, is_failure=True, terminate=True)
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 115, in message_printer
        error_message=get_error_message())
      File "/tmp/pip-install-ele2643x/esig/tools/install_helpers.py", line 59, in get_error_message
        f = open(filename, 'r')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-ele2643x/esig/tools/ERROR_MESSAGE'
    ----------------------------------------
```

**Comment by terrylyons** [comment]
Hi James, I think esig is currently based on a wheel that is manylinux2014 as the earliest. It should not be building anything. Thanks for letting us know. Can you try downloading the manylinux wheel and installing it locally.

**Comment by jambo6** [comment]
I need this for a codebase that I am pushing to someone else's code library. Their tests require things to pass on manylinux2010 and I need esig to be installed through a requirements.txt file. This is not for my local computer. 

Is there a way to get this to work on manylinux2010 using a `pip install -r requirements.txt` call?

**Comment by inakleinbottle** [comment]
The recombine library is not part of esig, only the interface is. I suspect the problem is that you don't have the recombine header and binary in order to correctly compile esig. Having said that, I don't understand why pip is trying to build from source instead of simply downloading the wheel.

**Comment by jambo6** [comment]
but given that there is no manylinux2010 wheel, won't it try to download from source?

**Comment by inakleinbottle** [comment]
Perhaps this is the problem. Regardless, if you have to build from source then the build will fail because you don't have access to the recombine library.

On a related note, the file _recombine.h seems to be missing from the source distribution. I will open a pull request to fix this.

**Comment by terrylyons** [comment]
The current versions were built on the assumption that manylinux 2014 would be early enough while allowing C++11 without work arounds. If performance is less important and you don’t need the recombine functionality then the older versions will work. (pre release 7). If not let us know.

Terry

On 8 Dec 2020, at 14:48, James Morrill <notifications@github.com> wrote:

﻿

I need this for a codebase that I am pushing to someone else's code library. Their tests require things to pass on manylinux2010 and I need esig to be installed through a requirements.txt file. This is not for my local computer.

Is there a way to get this to work on manylinux2010 using a pip install -r requirements.txt call?

**Comment by inakleinbottle** [comment]
The plot thickens regarding `_recombine.h`. I tested building the source distribution today on my machine. The header file `_recombine.h` should be included in the source distribution tarball for version 0.8.2. However, it seems that the 0.7.4 does not seem to have listed `_recombine.h` as a "depends" file, so it is not included in the source distribution. Moreover, the source tarball that is available on PyPI does not seem to include `_recombine.h`. This makes me think that an older version of setuptools does not take the "depends" keyword into account when collecting source files.

Indeed, I tested composing the sdist using Python3.7 on my local machine, with all other settings the same, and `_recombine.h` is missing from the resulting tarball.

**Comment by jambo6** [comment]
Hi, how's it going with the recombine issue? Is it likely to be fixed in the next version?

**Comment by inakleinbottle** [comment]
Hi, if you don't need the recombine functionality of esig, you can try pinning the dependency to esig 0.6.31, which was build with manylinux1 and should work in the manylinux2010 environment.

**Comment by jambo6** [comment]
If I create a new environment and run the following
```
pip install esig==0.6.31
python
>>> import esig 
>>> esig.stream2sig
AttributeError: module 'esig' has no attribute 'stream2sig'
```
This is true for any esig version less than 0.8.

Any ideas whats going on here?

**Comment by inakleinbottle** [comment]
The old version of esig did not have the functions exposed in the top level. You need to import the `tosig` module from esig and use the functions from there.
```python
from esig import tosig
tosig.stream2sig
```

**Comment by jambo6** [comment]
Thank you! Sorry I missed that.

Sorry but I have a new error on this one, it is failing because it cant find libboost. I assume the systems have libboost if they worked with 0.8.2, is there something else I need to specify in the installation?

**Comment by inakleinbottle** [comment]
Boost is a dependency of libalgebra, and it is supposed to be packaged into the wheel with esig. Can you provide more detailed output so I can see what is happening here.

**Comment by jambo6** [comment]
```
    Running setup.py install for esig: started
    Running setup.py install for esig: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/_internal/cpython-3.8.7/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_gbg1_p/esig_883a7de1044841e3a6b881afe0b3beaf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_gbg1_p/esig_883a7de1044841e3a6b881afe0b3beaf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_hcrigx/install-record.txt --single-version-externally-managed --compile --install-headers /opt/_internal/cpython-3.8.7/include/python3.8/esig
         cwd: /tmp/pip-install-g_gbg1_p/esig_883a7de1044841e3a6b881afe0b3beaf/
    Complete output (33 lines):
    esig_install> Starting esig installer...
    esig_install> Something went wrong! Please review the messages below to rectify the problem.
    esig_install>
    esig_install> We couldn't find one or more required libraries. It (or they) are listed below.
    esig_install> Please fix this problem before continuting.
    esig_install> Try using the --library-dirs argument when running the installer.
    esig_install>
    esig_install> Missing library/libraries:
    esig_install>     Package boost, library system (libboost_system or libboost_system-mt)
    esig_install>     Package boost, library thread (libboost_thread or libboost_thread-mt)
    esig_install>
    esig_install> General Information
    esig_install> ===================
    esig_install> If you see this message, compilation and installation unfortunately failed. If
    esig_install> building from source, the esig package requires the Boost C++ library to be
    esig_install> installed and correctly configured. Installation most likely failed because the
    esig_install> installer was not able to locate Boost.
    esig_install>
    esig_install> Please make sure you have done the following.
    esig_install> * Downloaded and installed a copy of Boost.
    esig_install> How you do this varies from platform to platorm.
    esig_install> * Provided the necessary paths to Boost include files and libraries.
    esig_install> This is only necessary when installing Boost to a non-standard
    esig_install> location.
    esig_install> If you do this, you can use the --include-paths and --library-paths
    esig_install> arguments.
    esig_install>
    esig_install> Once you have done this, esig should install successfully. For more
    esig_install> information, you can refer to the online documentation. It's available at
    esig_install> http://esig.readthedocs.io/en/latest/troubleshooting.html.
    esig_install>
    esig_install> Now terminating.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/_internal/cpython-3.8.7/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g_gbg1_p/esig_883a7de1044841e3a6b881afe0b3beaf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g_gbg1_p/esig_883a7de1044841e3a6b881afe0b3beaf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6_hcrigx/install-record.txt --single-version-externally-managed --compile --install-headers /opt/_internal/cpython-3.8.7/include/python3.8/esig Check the logs for full command output.
##[error]Bash exited with code '1'
```

**Comment by inakleinbottle** [comment]
Ah, there is no wheel for Python3.8 on esig 0.6.31 so it is trying to compile it from source, which will require you to have libboost in a location that can be found by Python setuptools. I suspect this is going to be tricky. Unfortunately, I don't have a good solution to offer you at this time.

**Comment by jambo6** [comment]
Ok, is there any other version I can use?

Otherwise, is there any chance of uploading a version of 0.8.2 with removal of the recombine functionality, assuming that will mean it works on manylinux2010? Otherwise, I have no way to proceed with this integration into sktime.

**Comment by inakleinbottle** [comment]
I think these builds of esig predate Python 3.8, so none of them are likely to have binary distributions that can be used. I don't know about removing recombine. It would require lots of changes to our build system to build the complete range of Python versions and architecture.

**Comment by terrylyons** [comment]
OK so that is the problem - when we built 6.31 (the last with manylinux based on centos 5.5) no-one was using python 3.8. After that we built with manylinux 2014 . Because you are using pip from python 3.8 you are looking for and not finding a wheel because there were no old wheels for python 3.8; that problem will be universal across all platforms (linux, windows,...). Trying to build 6.31 from code probably works - particularly on linux - however it is fragile and will require that your system has boost installed in the correct places.

**Comment by terrylyons** [comment]
To build successfully from source it needs boost installed as the error messages suggest.  If you can run 
sudo apt-get install libboost-all-dev

6.31 should just work (the dependencies on the later versions are more complex).

**Comment by terrylyons** [comment]
But if it is not your code installation that could be challenging. The easiest solution could be for us to go back to version 6.31 and add a wheel for python 3.8. Is that feasible?

**Comment by jambo6** [comment]
Sadly I do not believe I will be allowed to add 
```
sudo apt-get install libboost-all-dev
```
into the code. 

If it would be possible to get a wheel for 6.31 that would be great.

**Comment by rolyp** [comment]
Closing this issue as esig now builds on manylinux2010 instead of manylinux2014.

**Comment by terrylyons** [comment]
Congratulations!!!

Terry

On 24 Feb 2021, at 21:14, Roly Perera <notifications@github.com> wrote:

﻿

Closing this issue as esig now builds on manylinux2010 instead of manylinux2014.
